export { default as mountains } from 'assets/images/mountains.png'
export { default as mountainsFrontSide } from 'assets/images/mountains-front-side.png'
export { default as noiseBg } from 'assets/images/noise.png'
export { default as whiteBlocks } from 'assets/images/white-blocks.png'
export { default as whiteBlocksOld } from 'assets/images/white-blocks-bg--old.png'
export { default as lines } from 'assets/images/lines.svg'
export { default as desert } from 'assets/images/desert.png'
export { default as checkboxArrow } from 'assets/images/checkbox-arrow.svg'
export { default as personInCircle } from 'assets/images/person-in-circle.png'
export { default as handFromSky } from 'assets/images/hand-from-sky.png'

export { ReactComponent as LogoDottedSphereIcon } from 'assets/images/logo-dotted-sphere.svg'
export { ReactComponent as LogoSphereIcon } from 'assets/images/logo-sphere.svg'
export { ReactComponent as LogoText } from 'assets/images/logo-text.svg'
export { ReactComponent as AtomIcon } from 'assets/images/atom.svg'
export { ReactComponent as DNAIcon } from 'assets/images/dna.svg'
export { ReactComponent as MaterialIcon } from 'assets/images/material.svg'
export { ReactComponent as SpiralIcon } from 'assets/images/spiral.svg'
export { ReactComponent as DrugIcon } from 'assets/images/drug.svg'
export { ReactComponent as BioInformaticsIcon } from 'assets/images/bioinformatics.svg'
export { ReactComponent as InfoIcon } from 'assets/images/info.svg'

